#!/usr/bin/sh

#1)
valac --thread --pkg sfml-graphics-2 --pkg sfml-window-2 --pkg sfml-system-2 --pkg sfml-audio-2 --pkg gee-0.8 --pkg gio-2.0 --target-glib=2.32 -g --vapidir=vapi \
src/main.vala \
src/World/world.vala \
src/World/region.vala \
src/World/ground_types.vala \
src/World/block_types.vala \
src/World/position.vala \
src/World/eventmanager.vala \
src/World/particle.vala \
src/Entity/entity.vala \
src/Graphics/texture.vala \
src/Generation/noise.vala \
src/Generation/biomes.vala \
src/Generation/namegen.vala \
src/Display/display.vala \
src/Display/eventhandler.vala \
src/Display/render.vala \
src/Display/interface.vala \
src/Data/properties.vala \
src/Data/items.vala \
src/Data/inventory.vala \
src/Data/parser.vala \
src/Data/nmlparser.vala \
src/Data/modloader.vala \
src/Data/mods.vala \
src/consts.vala \
src/dynamiclist.vala \
-C

#Optional! Add:
#-X -lm -X -l -X csfml-graphics -X -l -X csfml-window -X -l -X csfml-system -X -l -X csfml-audio -g -X -fsanitize=address -o nilts
#above for debugging!

#2)
clang -c -g \
src/main.c \
src/World/world.c \
src/World/region.c \
src/World/ground_types.c \
src/World/block_types.c \
src/World/position.c \
src/World/eventmanager.c \
src/World/particle.c \
src/Entity/entity.c \
src/Graphics/texture.c \
src/Generation/noise.c \
src/Generation/biomes.c \
src/Generation/namegen.c \
src/Display/display.c \
src/Display/eventhandler.c \
src/Display/render.c \
src/Display/interface.c \
src/Data/properties.c \
src/Data/items.c \
src/Data/inventory.c \
src/Data/parser.c \
src/Data/nmlparser.c \
src/Data/modloader.c \
src/Data/mods.c \
src/consts.c \
src/dynamiclist.c \
 -Ilibraries/CSFML-2.1/include -Ilibraries/gee/include -Ilibraries/glib2/include

#3)
clang -o nilts \
main.o \
world.o \
region.o \
ground_types.o \
block_types.o \
position.o \
eventmanager.o \
particle.o \
entity.o \
texture.o \
noise.o \
biomes.o \
namegen.o \
display.o \
eventhandler.o \
render.o \
interface.o \
properties.o \
items.o \
inventory.o \
parser.o \
nmlparser.o \
modloader.o \
mods.o \
consts.o \
dynamiclist.o \
-lgee-0.8 -lgobject-2.0 -lglib-2.0 -lgio-2.0 -Llibraries/gee/lib -Llibraries/shared-lib -lcsfml-window -lcsfml-graphics -lcsfml-system -lcsfml-audio -lcsfml-network -lm \
-fsanitize=address

#NOT NEEDED AT THE MOMENT:
#-LCSFML-2.1/lib/gcc

LINES_C=`( find src -name '*.c' -print0 | xargs -0 cat ) | wc -l`

#4)
rm *.o
rm src/*.c
rm src/Display/*.c
rm src/World/*.c
rm src/Graphics/*.c
rm src/Generation/*.c
rm src/Entity/*.c
rm src/Data/*.c

LINES_VALA=`( find src -name '*.vala' -print0 | xargs -0 cat ) | wc -l`

echo "There are $LINES_VALA lines of Vala code in the src directory."
echo "There are $LINES_C lines of C code generated by the Vala code."

echo "Build complete, but not necessarily successful."
